common-workflow-language/cwl-v1.2

conformance_tests.yaml
tests/cat-tool-shortcut.cwl

Turns out `wc` command output format is not the same in different environments, which leads to different checksum and a failed test. I couldn't trace the root cause of the difference, it was the same command line in the same docker image, with the same environment variables inside the image but a slightly different format was created.

Change wc to cat in test for portability

---

CommandLineTool.yml

In v1.1 we expanded the set of allowed values to `null` and `array<File|Dir>`, bit it was not explicitly documented in the Dirent.entry doc, which might cause confusion to implementers (it already confused one developer which is why this PR was made :) )

Clarify behavior of Dirent.entry for all allowed values

---

CommandLineTool.yml

A colleague was confused because `enableReuse` is a required field, it may make more sense to state what happens if the whole requirement is unspecified

Update WorkReuse doc

---

Workflow.yml

Opened this PR mainly for discussion on if we should rename the method and what the new name should be. Reason for the rename request is that the behavior of this method is not intuitive (at least it wasn't for me when I implemented these, as initially I though only_non_null returns all non null values). 
I also did a small experiment where I listed the pickValue method names to three colleagues and asked them which method does what. All three of them couldn't figure out what would be the difference between `only_non_null` and `all_non_null`.
In the PR the proposed name is `exactly_one_non_null`, I was thinking also maybe `the_only_non_null`.
@kaushik-work @mr-c @tetron happy to hear your thoughts on this. I guess we can discuss on the meeting tuesday

Rename only_non_null pickValue method

---

conformance_tests.yaml

Brings in https://github.com/common-workflow-language/cwl-v1.1/pull/72/files and starts to work on new CWL 1.2 tests.
I don't know what to do about the duplicate test below - the tests (230, 231) had different labels and tags but they were the same test. A copy-paste problem I assume? Because of the ``id``s, it will break the ordering to just remove it so I just appending _duplicate to the new label for the second one.
I guess we don't promise the ordering of ``id`` doesn't have holes- should I just remove it?

Fix up missing/duplicate labels and missing tags (1/n)

---

tests/timelimit-wf.cwl
tests/timelimit4-wf.cwl

As per issue https://github.com/common-workflow-language/cwl-v1.2/issues/51 the two workflows used in the  `timelimit_from_expression_wf` and `timelimit_basic_wf` tests have syntax errors. This PR fixes #51

Fix broken test workflows re: issue #51

---

CONFORMANCE_TESTS.md
conformance_tests.yaml

This PR adds text to the CONFORMANCE_TESTS.md file explaining when to use particular tags in the conformance_tests.yaml.

Explain use of tags in conformance tests

---

conformance_tests.yaml

This request adds a tag `load_listing` for [`LoadListingRequirement`](https://www.commonwl.org/v1.2/Workflow.html#LoadListingRequirement).

Add `load_listing` tag for the conformance tests

---

run_test.sh

This request fixes #70.
Basically it copies `run_test.sh` in [common-workflow-language/common-workflow-language](https://github.com/common-workflow-language/common-workflow-language) but includes several minor changes:
- delete `DRAFT` stuff
- introduce `CWL_VER` but only used in the message in `runtest` function
- fix `--self` to check `tests` directory recursively
I confirmed that `--timeout` (only positive cases), `--self` (checked it recursively validates the documents), `--badgedir` and `--tags` work correctly.

Update run test.sh

---

.github/workflows/ci.yml

This request adds `.github/workflows/ci.yml`.
It validates:
- `conformance_tests.yaml` using `cwltest-schema.yml`
- Note: CI downloads the schema from the following link. Please let me know if there is more appropriate link for the schema.
- https://raw.githubusercontent.com/common-workflow-language/cwltest/main/cwltest/cwltest-schema.yml
- all the CWL documents in `tests` directory

Add CI settings for Github Actions

---

CommandLineTool.yml

This request fixes #82 by clalifying disruptive changes are not allowed without `inplaceUpdate: true`.

Clarify InitialWorkDirRequirement.writable

---

conformance_tests.yaml
tests/synth-file-job.yml
tests/synth-file.cwl

Adds a basic test to check that a file generated with inline contents exists and has the expected contents (using `cat`).
Based on https://github.com/common-workflow-language/cwltool/issues/369 .

Add test to ensure a synthetic file is created properly.

---

tests/iwd/test-index.yaml

The tests in `tests/iwd` didn't have labels so could not be filtered by name. I have converted the id to labels and given them ids in the same style as other subdirs of tests (à la conditionals)
When this merges, the conformance tests should pass in CI.

InitialWorkDirRequirement tests label/id fix

---

run_test.sh

When following directions here, https://www.commonwl.org/v1.2/, to execute the test script, run_test.sh fails on Mac (Darwin):
```
$ ./run_test.sh 
./run_test.sh: line 160: greadlink: command not found
--- Running CWL Conformance Tests v1.2 on  ---
./run_test.sh: line 144: : command not found
usage: cwltest [-h] --test TEST [--basedir BASEDIR] [-l] [-n N] [-s S] [-N N]
[-S S] [--tool TOOL] [--only-tools] [--tags TAGS] [--show-tags]
[--junit-xml JUNIT_XML] [--junit-verbose]
[--test-arg cache==--cache-dir] [-j J] [--verbose]
[--classname CLASSNAME] [--timeout TIMEOUT]
[--badgedir BADGEDIR] [--version]
...
cwltest: error: argument --tool: expected one argument
1 tool tests failed
```
When I run the script with 'bash -ex', the if statement resolves to '[' Darwin = Linux ']':
```
+ '[' Darwin …
```

Fix run_test.sh to run on Mac (Darwin)

---

tests/loadContents/cwloutput-nolimit.cwl

Which makes this conformance test less mean
Fixes #120

fix cwloutput-nolimit test's outputs to match the cwl.output.json results 

---

concepts.md

Fixes https://github.com/common-workflow-language/common-workflow-language/issues/206
Supersedes https://github.com/common-workflow-language/common-workflow-language/pull/929
Quoting the superseded PR:
>Hi,
>
>Having a go at the Barn Raising issue about ES expression and ES function body. At first I wrote a longer version with an example `$(new Date())` for expression, and a longer `${var dt = new Date(); dt.setDate(dt.getDate() - 2); return dt}` function body that returns a date minus 2 days.
>
>But I think it became too specific and made the section even longer? I also thought that perhaps the comparison could go into a NOTE section, but didn't find any such section nearby, so went with the simpler approach.
>
>Happy to amend as per feedback :+1: 
>
>Thanks
>Bruno
>
>~p.s.: this PR also …

Clarify $() and ${}

---

concepts.md
conformance_tests.yaml
tests/length_non_array_input.yml
tests/params_broken_length_of_non_list.cwl
tests/params_broken_null.cwl
tests/params_input_length_non_array.cwl

This aims to address https://github.com/common-workflow-language/common-workflow-language/issues/761 at least on the documentation level. The associated test should be expanded to ensure that incorrect usages are not allowed (e.g. `$(null.something)`).

Clarify parameter reference: null and array length

---

Process.yml
conformance_tests.yaml
tests/A:Gln2Cys
tests/colon:test.cwl
tests/colon:test:job.yaml
tests/colon_test_output.cwl
tests/colon_test_output_job.yaml

Currently, `cwltool` is too conservative and it does not permit pathnames with `:` (the colon) without the flag `--relax-path-checks`
While the CWL standards do allow for excluding some characters in pathnames, the colon is not one of them:
https://www.commonwl.org/v1.2/CommandLineTool.html#File
under `path`:
> If the `path` contains [POSIX shell metacharacters](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_02) (`|`, `&`, `;`, `<`, `>`, `(`, `)`, `$`, `` ` ``, `\`, `"`, `'`, `<space>`, `<tab>`, and `<newline>`) or characters not allowed for [Internationalized Domain Names for Applications](https://tools.ietf.org/html/rfc6452) then implementations may terminate the process with a `permanentFailure`.
(The text is the same in CWL v1.0 and v1.1)

Test for colon in paths

---

conformance_tests.yaml
tests/record_outputeval.cwl
tests/record_outputeval_nojs.cwl

Inspired by https://github.com/common-workflow-language/cwltool/pull/1625

Test for outputEval on a record type itself, not its fields

---

concepts.md
invocation.md
salad/schema_salad/metaschema/salad.md

Cloning more repositories, importing code into a new IDE workspace, and running local linters as part of #54 . Found a few typos in the spec with the WebStorm spell checker inspection. Not sure about those `an` vs. `a`, so happy to amend the PR if needed :+1: 
Thanks!
Bruno

Fix a few typos (automatic IDE spellchecker)

---

conformance_tests.yaml

Part of #54
Confirmed the IDs are not sequential, as we have missing numbers in between tests. Also checked the schema salad in cwltest, and it allows for `null`s. I think there's some work in cwltest to deprecate ids and use labels - https://github.com/common-workflow-language/cwltest/issues/110
So I believe we can safely remove the duplicate test, as long as CI doesn't complain :crossed_fingers:

Remove duplicate test

---

conformance_tests.yaml
tests/runtime-outdir.cwl

Closes #109 
First time writing a conformance test for 1.2.1 :tada: 
After installing dependencies and learning how to use `run_tests.sh`, looked at the example in the issue and at existing tests to create this simple test.
Let me know if there are any mistakes, or good practices that I haven't used. I'm looking at the easy issues for now to learn how to write conformance tests.
Thanks!
Bruno

Add conformance test that verifies we can use runtime outdir with output glob

---

conformance_tests.yaml

This request contains the following changes:
- remove `required` tag from the tests that has process requirements in `requirements` field
- add `inline_javascript` tag to the tests that has `InlineJavascriptRequirement` in `requirements` field

Fix tags for conformance tests

---

Workflow.yml

This request is to solve [common-workflow-language/common-worflow-language#760](https://github.com/common-workflow-language/common-workflow-language/issues/760) by adding the description of the case of `string`.

Add extra description of `run` field

---

run_test.sh

It solves #125.
`cwltest -l` is already executable without `cwl-runner` so this request just skips checking and executing `cwl-runner.`

Fix `-l` to list tests without `cwl-runner`

---

conformance_tests.yaml

This request fixes tags for tests that must be tagged with `workflow` rather than `command_line_tool`.

Fix tags for workfows

---

conformance_tests.yaml

This request adds `label` fields to the tests that lacks `label` field or string-based `id` field.
It is a preparation of solving https://github.com/common-workflow-language/cwltest/issues/110.

Add missing `label` field

---

concepts.md

Found when I was re-generating the conformance HTML in schema salad for https://github.com/common-workflow-language/schema_salad/pull/543

Remove stray backtick in the docs

---

CommandLineTool.yml

Added the link to `Dirent`, and fixed a typo.

Add link to Dirent and fix typo

---

CommandLineTool.yml
conformance_tests.yaml
invocation.md
tests/stdout_chained_commands.cwl

Closes #95 
Hadn't used `ShellCommandRequirement` yet, it looks useful!
Added a new conformance test, and tried to update the spec. I noticed that text is often repeated in the specification, which I find useful, so I did the same here. The docs for `stdout` received the same text, but I tried to explain a little better at the Execution section for running the tool.
Cheers
-Bruno

Add new test for chained commands, update the specification wording

---

tests/metadata.cwl

Was thinking about https://github.com/common-workflow-language/common-workflow-language/issues/743, and my initial thought was to use the output of `--pack metadata.cwl` which would include the metadata. But couldn't figure out a way to reference that in the test output (tried to think in a way to use some JS expression for that, but I don't think the metadata is loaded in the JS expr context.)
So I went with the other alternative mentioned in the issue, updating the test documentation to show the intention of testing the metadata. I think the previous doc could be misleading, making the reader think it was about printing the output of `cat` and maybe using it in the test…
Or maybe there's some better way to update that test?

Update the doc and use "true" as base command for the metadata test

---

Process.yml
concepts.md
invocation.md

For https://github.com/common-workflow-language/common-workflow-language/issues/914.
`concepts.md` is included by `Workflow.yml` and `Process.yml`, so the link should render OK. But I'll try to render it before marking as ready for review.

Add glossary and clarification on opaque strings and identifiers

---

Workflow.yml
conformance_tests.yaml
tests/output_reference_workflow_input.cwl

Closes https://github.com/common-workflow-language/common-workflow-language/issues/763
Not sure if an example would be useful (haven't seen other examples). Or maybe better to leave the specification simpler and add details in the user guide.

Mention that we can refer to workflow level inputs in output parameter outputSource

---

conformance_tests.yaml
tests/schemadef_types_with_import-job.json
tests/schemadef_types_with_import-tool.cwl
tests/schemadef_types_with_import-wf.cwl
tests/schemadef_types_with_import_readgroup.yml

For https://github.com/common-workflow-language/common-workflow-language/issues/703
Used example written by @jeremiahsavage (thanks!). It doesn't output anything, but validates that it could import the types successfully.
Or if we prefer to test for some output, I can rewrite it to output something.
Cheers
Bruno

Add test for SchemaDefRequirement with a workflow and the types containing an $import statement

---

Process.yml

Closes #117 
Looks like the `Process` section includes/requires another document where the `id` field is defined. I'm guessing this works similar to OOP in Python/Java, and that I can specify the `id` in `Process`.
Will render the site with this change to confirm it's working as expected...

Clarify process id field ($graph only)

---

salad/schema_salad/metaschema/vocab_res.yml

Before
https://www.commonwl.org/v1.2/SchemaSalad.html#Vocabulary_resolution
After

fix over-indented list interpreted as code + typo (must be replace[d])

---

concepts.md

Fixes https://github.com/common-workflow-language/cwl-v1.2/issues/206
Instead of the plain strings used here: https://www.commonwl.org/v1.2/CommandLineTool.html#Parameter_references
Changes render as follows: 
Regarding the mention https://github.com/common-workflow-language/cwl-v1.2/issues/206#issuecomment-1302255446, I could find any other reference to `::` to adjust for `::=` other than in the table itself. 
Let me know (point me toward where) if the is somewhere specific to update.

add code format to parameter references table definitions 

---

conformance_tests.yaml
tests/capture-dirs.cwl
tests/capture-files-and-dirs.cwl
tests/capture-files.cwl

Check that an error is thrown if `File` and `Directory` types are not correctly specified.

Added conformance tests for File and Directory glob

---

Workflow.yml
concepts.md

Up to CWL v1.2, type-checking never occurs for ExpressionTool output objects in the reference implementation. Therefore, it must be explicitly stated in the specification. The goal is then to fix this behaviour in CWL >= v1.3.

Document that ExpressionTool outputs are always valid

---

Process.yml
concepts.md
invocation.md

Substitute URI with IRI in docs

---

.github/config/wordlist.txt
.github/workflows/spellcheck.yml
conformance_tests.yaml
salad/schema_salad/metaschema/field_name_schema.yml
salad/schema_salad/metaschema/ident_res_schema.yml
salad/schema_salad/metaschema/import_include.md
salad/schema_salad/metaschema/link_res.yml
salad/schema_salad/metaschema/metaschema.yml
salad/schema_salad/metaschema/metaschema_base.yml
salad/schema_salad/metaschema/salad.md
salad/schema_salad/metaschema/typedsl_res.yml
tests/floats_small_and_large.cwl
tests/floats_small_and_large_nojs.cwl
tests/revsort-packed.cwl
tests/revsort.cwl
tests/sorttool.cwl

Add tests for decimal representation of very big and very small numbers

---

CommandLineTool.yml

As reported at https://cwl.discourse.group/t/a-typo-on-commandlinetool-specification-stdin-example/797

Fix typo {} vs ()

---

.github/workflows/ci.yml
.gitignore
conformance_tests.yaml
json-schema/cwl.yaml
requirements-jsonschema-test.txt
run_test.sh
tests/json_schema/test_cwl_schema.py
tests/loadContents/test-index.yaml
tests/mixed-versions/test-index.yaml

- Adds CWL JSON schema
- Adds test suite to GitHub Actions CI with pytest to validate the JSON schema against conformance test items
- Fix minor indentation issues in `run_test.sh`
- Closes https://github.com/common-workflow-language/cwl-v1.2/issues/253
- Closes https://github.com/common-workflow-language/cwl-v1.2/issues/251 (2 failing test cases)
- Relates to https://github.com/opengeospatial/ogcapi-processes/pull/327
- Relates to https://github.com/opengeospatial/ogcapi-processes/pull/329

Add JSON schema for CWL and conformance tests validating it

---

CommandLineTool.yml
Process.yml
Workflow.yml
concepts.md
cwl-runner.cwl
index.md

v1.2.1 errata

---

run_test.sh

This request is to support for markdown report feature that was implemented in https://github.com/common-workflow-language/cwltest/pull/209.
Related:
- common-workflow-language/common-workflow-language#958 and common-workflow-language/cwl-v1.1#85

Add support for markdown report

---

CommandLineTool.yml
Workflow.yml

Schema-salad doesn't handle backticks in headings correctly
Added ` tests` to the end of the headings to ensure that the links are unique

1.2.1: fix some heading so that the links work. 
