common-workflow-language/cwl-v1.2

Process.yml
salad/schema_salad/metaschema/sfdsl_res.yml

Cover https://github.com/common-workflow-language/common-workflow-language/issues/891

Add doc to SecondaryFileSchema

---

conformance_tests.yaml
tests/mixed-versions/hello.txt
tests/mixed-versions/hello.txt.2
tests/mixed-versions/invalid-tool-v10.cwl
tests/mixed-versions/invalid-tool-v11.cwl
tests/mixed-versions/invalid-wf-v10.cwl
tests/mixed-versions/invalid-wf-v11.cwl
tests/mixed-versions/invalid-wf-v12.cwl
tests/mixed-versions/test-index.yaml
tests/mixed-versions/tool-v10.cwl
tests/mixed-versions/tool-v11.cwl
tests/mixed-versions/tool-v12.cwl
tests/mixed-versions/wf-v10.cwl
tests/mixed-versions/wf-v11.cwl
tests/mixed-versions/wf-v12.cwl

Also check that new syntax isn't allowed in documents with older
version.
Re-do of https://github.com/common-workflow-language/cwl-v1.2/pull/24

Test mixed workflow / tool versions.

---

CommandLineTool.yml
Workflow.yml
concepts.md

Define data link.  Also specify default interpretation of exit codes.

---

CommandLineTool.yml
conformance_tests.yaml
tests/storage_float.cwl

refs #38 and https://github.com/common-workflow-language/cwltool/pull/1327

Resource floats

---

conformance_tests.yaml
tests/conditionals/test-index.yaml
tests/loadContents/test-index.yaml
tests/mixed-versions/test-index.yaml
tests/secondaryfiles/test-index.yaml
tests/string-interpolation/test-index.yaml

Fix more annotation issues for conformance tests.

---

conformance_tests.yaml

This request adds `work_reuse` tag for [`WorkReuse`](https://www.commonwl.org/v1.2/Workflow.html#WorkReuse).

Add work_reuse tag

---

CommandLineTool.yml
Operation.yml
Process.yml
Workflow.yml

Re-do of #62 against the v1.2.1-proposed branch

all Requirement classes should be static strings

---

CommandLineTool.yml
Process.yml

explicitly allow an int where we allow a long

Long or int

---

Process.yml
concepts.md

Fix #138: `$schema` to `$schemas`

---

conformance_tests.yaml
tests/cat-from-dir-with-literal-file-in-subdir.yaml
tests/cat4-from-dir.cwl

Test idea from @mvdbeek as part of the Galaxy CWL implementation

Test for literal directory with literal subdirectory.

---

conformance_tests.yaml
tests/paramref_arguments_roundtrip.cwl

From https://github.com/common-workflow-language/cwltool/pull/1623

Allow records with defaults to be accepted, also type longs

---

README.md

Building the website for the first time, but realized I was looking at the wrong `website.sh` script :+1:

Update readme: Use main branch

---

.github/workflows/spellcheck.yml

Quick fix for the YAML syntax and configuration location.
Thanks to @mr-c for letting me know it wasn't working as expected :bow: 
Tested on my fork: https://github.com/kinow/cwl-v1.2/pull/1

Fix Spellcheck action YAML syntax

---

Workflow.yml

Closes https://github.com/common-workflow-language/cwl-v1.2/issues/101
Rendered website:

Add note about cwl-upgrader in the Workflow changelog

---

concepts.md

Reading the spec again with calm today found a few links that could be improved :+1:

Update links used in concepts

---

concepts.md

This request fixes #197 by adding missing process requirements.

Add inheritable process requirements for CLT

---

CommandLineTool.yml

As per https://github.com/crim-ca/weaver/pull/506#discussion_r1036766400

fix typo in ResourceRequirement.coresMin description

---

Workflow.yml

fix workflow scatter typos

---

.github/workflows/ci.yml
.github/workflows/cwltool.yml

ci: use cwltest pytest plugin for better speed

---

tests/loadContents/test-index.yaml

All loadContents tests are required

---

json-schema/cwl.yaml
requirements-jsonschema-test.txt

Fixes issue identified in https://github.com/common-workflow-language/cwl-v1.2/pull/264#issuecomment-1682409444

add missing `Any?` and `Any[]?` CWL types to JSON schema

---

json-schema/cwl.yaml

fix schema typo
